language: rust
rust: [stable, beta, nightly]
cache: cargo
env:
  global:
    - RUSTFLAGS="-Z external-macro-backtrace"
  matrix:
    - RELEASE_FLAG=""
    - RELEASE_FLAG="--release"

install:
  - "export FEATURE_STABLE=$(cargo --version | grep nightly >/dev/null || echo \"--features stable\")"
  - "rustup component add rustfmt --toolchain $(rustup show active-toolchain | cut -d ' ' -f 1)"

script:
  - cargo check --verbose --all $RELEASE_FLAG $FEATURE_STABLE
  - cargo test --verbose --all $RELEASE_FLAG $FEATURE_STABLE
  - cargo doc --verbose --all $RELEASE_FLAG $FEATURE_STABLE
  - cargo fmt --all -- --check
