[workspace]
members = [
	".",
	"codegen",
]

[package]
name = "include-flate"
version = "0.1.0"
authors = ["SOFe <sofe2038@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/SOF3/include-flate.git"
homepage = "https://github.com/SOF3/include-flate"
description = "A variant of include_bytes!/include_str! with compile-time deflation and runtime lazy inflation"

[dependencies]
include-flate-codegen = {version = "0.1.0", path = "codegen"}
lazy_static = "1.3"
libflate = "0.1.26"
