[package]
name = "include-flate-codegen"
version = "0.1.2"
authors = ["SOFe <sofe2038@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/SOF3/include-flate.git"
homepage = "https://github.com/SOF3/include-flate"
description = "Macro codegen for the include-flate crate"

[lib]
proc-macro = true

[dependencies]
libflate = "0.1.26"
proc-macro2 = "0.4.30"
quote = "0.6.13"
syn = {version = "0.15.44", features = ["full"]}
