[package]
name = "include-flate-codegen"
version = "0.1.3"
authors = ["SOFe <sofe2038@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/SOF3/include-flate.git"
homepage = "https://github.com/SOF3/include-flate"
description = "Macro codegen for the include-flate crate"

[lib]
proc-macro = true

[dependencies]
libflate = "0.1.26"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
proc-macro-hack = { version = "0.5.9", optional = true }

[features]
stable = ["proc-macro-hack"]
